Civil-Service-Human-Resources/lpg-management

.dockerignore, Dockerfile, environ/ci
- adding npm install to ci 
- adding npm start command to Dockerfile
=> fix docker config

views/assets/js/char-count.js, views/component/course/styles.scss, views/component/course/template.njk, views/component/menu-box/styles.scss, views/page/course.html
- Moved char-count.js to a more suitable location
- Moved course overview to right hand panel & refactored styling as per LPFG-532
- Added a back button. This currently uses an onClick event to take the user back. This will be changed at a later date
- Added course details, learning outcomes and modules sections. Modules is empty and hardcoded. Details and learning outcomes are actual data.
=> Refactor course overview

views/component/menu/template.njk
=> fixing course link

views/component/Page.njk
added `window.GOVUKFrontend.initAll()` to page.njk
=> fixed: mobile menu issue

src/controllers/audience/audienceController.ts, src/csrs/service/csrsService.ts, test/unit/csrs/service/csrsServiceTest.ts, views/page/course/audience/add-interests.html, views/page/course/audience/add-organisation.html, views/page/course/audience/audience-type.html, views/page/course/audience/configure-audience.html
- routerPaths set (& fixed) for interests in audienceController.ts
- getInterests() added to csrsService.ts
- added template for add-interests.html
- fixed link hrefs for some audience files
=> LPG-796 Interests 

views/component/phaseBanner/template.njk
- Added href for phase banner feedback link
=> LPFG-805 url added to phase banner feedback link

views/component/policyList/template.njk, views/component/tandcList/template.njk, views/page/course/course-preview.html, views/page/learning-provider/learning-provider-overview.html
- Fixed styling issues on learning provider overview page
- Added default value for learning provider name if unspecified
=> Lpfg 807 learning provider overview styling fixes

src/controllers/module/event/eventController.ts, test/unit/controllers/module/event/eventControllerTest.ts, views/page/course/module/events/event-location.html, views/page/course/module/events/events-overview.html
=> LPFG-678: Edit Location & availability 

views/assets/styles/_forms.scss, views/page/course/course-details.html, views/page/course/course-title.html
- added padding to both 'add course' forms
- added padding to submit button on both forms
=> LPFG-811 fixed padding on course forms

views/page/course/course-preview.html
- Removed file and content links from the edit menu (course overview)
=> removed file and content from edit links (course preview)

src/learning-catalogue/model/course.ts, src/learning-catalogue/model/factory/courseFactory.ts, src/learning-catalogue/model/status.ts, test/unit/learning-catalogue/model/factory/courseFactoryTest.ts
Added Status domain enum and added as property in Course class.
=> LPFG-889: Add status field to domain classes in lpg-management

src/controllers/module/fileController.ts, src/locale/en.json, test/unit/controllers/module/fileControllerTest.ts, views/component/Page.njk, views/page/course/course-preview.html, views/page/course/module/add-module.html, views/page/course/module/events/event-dateRange-edit.html, views/page/course/module/module-file.html
- updating nav bar and footer links
- removing audiences link from preview header
- updating content of file/mp4/elearning upload forms
=> Fix misc fixes

views/assets/styles/_global.scss, views/assets/styles/main.scss, views/component/courseDetails/styles.scss, views/component/courseDetails/template.njk, views/component/list/styles.scss, views/component/list/template.njk, views/component/status/macro.njk, views/component/status/styles.scss, views/component/status/template.njk, views/component/statusWithLabel/macro.njk, views/component/statusWithLabel/styles.scss, views/component/statusWithLabel/template.njk, views/page/course/course-overview.html, views/page/index.html
- New status component
- New status with label component
- Added course status to home page course list
- Added course status to course overview
- Refactored course listing. Removed table and placed in a ul as per access needs
- Fixed word break/word wrap issue (again)
=> LPFG-917 course status front end

src/controllers/module/moduleController.ts, src/learning-catalogue/index.ts, src/server.ts, test/unit/controllers/module/moduleControllerTest.ts, test/unit/learning-catalogue/indexTest.ts, views/page/course/module/add-module.html
- ability to delete a module
- updating text on the `add module` view
- prettier formatting
=> LPFG-846: delete module

package.json, views/assets/styles/_forms.scss, views/assets/styles/_global.scss, views/component/list/styles.scss, views/component/textarea/template.njk, views/page/course/course-details.html
- Updated gds front end toolkit
- Refactored textarea component to use the new character count gds component
=> LPFG-651-fix char count console error

src/learning-catalogue/index.ts, test/unit/learning-catalogue/indexTest.ts
- fixing search service method
=> fix-fix-search-list

views/assets/styles/page/_configure-audience.scss
- Small css fix for truncated text when all orgs are added on configure audience page
=> LPFG-1096 Truncated text bug

views/component/phaseBanner/template.njk
=> LPFG-1095 change the phase banner text

views/page/course/module/add-module.html
- Changed text on Continue button on add module page to 'Return to course'
=> Lpfg 1001 button rewording

views/assets/styles/page/_add-module.scss
- Fixed margin on add new event t emplate
- Also fixed repeating background-image bug on module handle
=> Lpfg 1150 padding fix

views/component/status/styles.scss, views/page/course/module/events/events-overview.html
- Change colour of invite attendee button from blue to green
=> LPFG-1197 Invite attendee button colour

views/assets/styles/_global.scss
- removed custom padding from red button
=> Lpfg 1194 delete button sizing

views/page/course/course-details.html
changed back button redirect location when editing course details
=> LPFG-1232 Course content back button

views/page/course/module/module-link.html
=> LPFG-1250 hint for url input

views/page/course/course-preview.html
- Changed back button location to redirect to course overview page
=> LPFG-1264 back button for preview & edit page

src/controllers/module/fileController.ts, src/learning-catalogue/model/factory/courseFactory.ts
If no file type has been set, then no file has been changed, so keep the file type already set in the module.
=> LPFG-1215: Editing files set file type to file

src/locale/en.json
- changed error message for incomplete URL
=> LPFG-1250 Changed error messages

views/component/Page.njk, views/component/nav/template.njk
Updated footer links to be consistent with the other services and move the "built by" link below the list of links.
=> LC-113 Contact us page

src/lib/errorHandler.ts, src/server.ts
- handling 401 responses so that the error page is not thrown when a user's token has expired.
=> LC-163: fix-auth-issues

src/controllers/reportingController.ts, src/report-service/index.ts, test/unit/controllers/reportingControllerTest.ts, test/unit/report-service/indexTest.ts, views/page/reporting/index.html
- Added CSV report for learner record
- Mocha and unit tests added
- Renamed booking management report functions
- Form to query report between 2 dates
=> LPFG-290: Learner Record Report

src/identity/auth.ts, src/identity/identityService.ts, src/server.ts
=> fix: fixing logout

views/assets/styles/_global.scss, views/page/reporting/index.html
- Added ul subclass to display bullet points
- Reformatted descriptions for MI and Learner Record reports
=> LC-180: Reporting - Reformat report descriptions

src/controllers/audience/audienceController.ts, src/server.ts, test/unit/controllers/audience/audienceControllerTest.ts, views/assets/styles/_forms.scss, views/page/course/audience/add-organisation.html, views/page/course/audience/configure-audience.html
- updating audience organisations to support multiple orgs
=> LC-241: updating audience orgs to support multi organisations

package.json
- fixing lodash package vulnerability https://github.com/lodash/lodash/pull/4336
=> fix-lodash-vulnerability

src/controllers/audience/audienceController.ts, src/controllers/organisationController.ts, src/csrs/csrsConfig.ts, src/csrs/service/csrsService.ts, test/unit/controllers/organisationControllerTest.ts, test/unit/csrs/service/csrsServiceTest.ts, views/component/audiences/template.njk
=> LC-244: audience improvements

src/report-service/reportServiceConfig.ts
- increasing report service timeout
=> fix-report-timeout

package.json, src/controllers/audience/audienceController.ts, src/controllers/module/event/eventController.ts, src/server.ts, test/unit/controllers/module/event/eventControllerTest.ts
Bumped appInisghts version
Fixed transpiler issues
=> Added appInsights at the top of server.js

src/controllers/module/fileController.ts, src/controllers/module/linkModuleController.ts, src/controllers/module/youtubeModuleController.ts, src/learning-catalogue/model/eLearningModule.ts, src/learning-catalogue/model/factory/linkFactory.ts, src/learning-catalogue/model/factory/moduleFactory.ts, src/learning-catalogue/model/fileModule.ts, src/learning-catalogue/model/linkModule.ts, src/learning-catalogue/model/videoModule.ts, views/assets/styles/_forms.scss, views/page/course/module/module-file.html, views/page/course/module/module-link.html, views/page/course/module/module-youtube.html
- https://cshrdigitalandanalysis.atlassian.net/browse/LC-235
- updating controllers, entities, factories and templates to include new Associated Learning field
- replacing https://github.com/Civil-Service-Human-Resources/lpg-management/pull/224/files and https://github.com/Civil-Service-Human-Resources/lpg-management/pull/228
=> LC-235 - adding new associated learning attribute for modules

src/learning-catalogue/model/audience.ts, src/learning-catalogue/model/course.ts, test/unit/lib/courseServiceTest.ts, views/component/courseDetails/template.njk, views/page/course/course-visibility.html
- https://cshrdigitalandanalysis.atlassian.net/browse/lc-255
- update content for private closed courses
- replacing https://github.com/Civil-Service-Human-Resources/lpg-management/pull/228
=> LC-255 - content for private/closed courses

src/controllers/courseController.ts, src/learning-catalogue/model/course.ts, src/learning-catalogue/model/event.ts, src/learning-catalogue/model/factory/courseFactory.ts, src/learning-catalogue/model/factory/moduleFactory.ts, src/lib/dateTime.ts, src/lib/pagination.ts, test/unit/controllers/agencyTokenControllerTest.ts, test/unit/controllers/courseControllerTest.ts, test/unit/controllers/homeControllerTest.ts, test/unit/controllers/learningProvider/learningProviderControllerTest.ts, test/unit/controllers/module/event/eventControllerTest.ts, test/unit/learning-catalogue/model/courseTest.ts, test/unit/learning-catalogue/model/factory/moduleFactoryTest.ts, test/unit/learning-catalogue/validator/moduleValidatorTest.ts
Duration logic implementation for face to face modules.
=> Duration impl for f2f modules

views/page/organisation/add-edit-agency-token.html
Fixes for Accessibility requirements.  The Wave Evaluation Tool, chrome extension highlighted these issues.
- Fixes for alerts about Orphaned form labels.
- Fixes for alerts about labels for hidden input elements in forms.
- Fixes for error about elements in forms.
=> Bug fix lc 14 accessibility

src/controllers/courseController.ts
Pick duration from the first event in the module.
Assumption: Events are chronologically sorted inside a module.
=> Hotfix course preview duration fix

src/controllers/skills/skillsController.ts, src/csrs/service/csrsService.ts, views/assets/styles/page/_quiz.scss, views/page/skills/add-new-question.html, views/page/skills/skills.html
When a user go to the Manage quiz page, then there is a logic that checks if the user has set profession in their profile and if so, then it will load the skills quiz for that profession. If the profession is not set then it will show an error message worning the user to set the profession
=> LC-466: adding profession specific logic

src/controllers/skills/skillsController.ts, views/page/skills/edit-quiz-description.html, views/page/skills/skills.html
Made a template for the edit quiz description and make the node connection.
Note: https://github.com/Civil-Service-Human-Resources/lpg-management/pull/247 Needs to be merged to release-skills-features first then this branch.
=> Lc 532 adding description to quiz

package-lock.json, package.json, src/config/appConfig.ts, src/config/index.ts, src/identity/auth.ts, src/server.ts, test/unit/learning-catalogue/model/courseTest.ts
idt-release-2.0 - Release went live successfully so now it is ready to merge.
=> idt-release-2.0

src/applicationContext.ts, src/config/index.ts, src/learner-record/learnerRecordConfig.ts, src/learning-catalogue/learningCatalogueConfig.ts, src/report-service/reportServiceConfig.ts, src/youtube/youtubeConfig.ts, test/unit/learner-record/learnerRecordConfigTest.ts, test/unit/learning-catalogue/learningCatalogueConfigTest.ts
http response timeout for learner-record is increased from 15 seconds to 30 seconds
=> LC-848 http response timeout for learner-record is increased

src/applicationContext.ts, src/config/index.ts, src/report-service/reportServiceConfig.ts
Pull request created in: https://cshrdigitalandanalysis.atlassian.net/browse/LC-886 by the Git Integration for Jira app.
=> LC-886: dt-feature-LC-886-configure-report-service-timeout

src/learning-catalogue/model/placeholderDate.ts, views/page/reporting/index.html
Pull request created in: https://cshrdigitalandanalysis.atlassian.net/browse/LC-887 by the Git Integration for Jira app.
=> LC-887: idt-feature-LC-887-update-reporting-end-date

src/applicationContext.ts, src/config/index.ts, src/csrs/csrsConfig.ts, src/csrs/model/organisationalUnitFactory.ts, src/identity/identityConfig.ts, src/learner-record/learnerRecordConfig.ts, src/learning-catalogue/learningCatalogueConfig.ts, src/youtube/youtubeConfig.ts, src/youtube/youtubeService.ts, test/unit/identity/agencyTokenCapacityUsedHttpServiceTest.ts, test/unit/learner-record/indexTest.ts, test/unit/learner-record/learnerRecordConfigTest.ts, test/unit/learning-catalogue/indexTest.ts, test/unit/learning-catalogue/learningCatalogueConfigTest.ts, test/unit/lib/http/jsonRestServiceTest.ts, test/unit/lib/http/oauthRestServiceTest.ts, test/unit/youtube/youtubeRestServiceTest.ts, test/unit/youtube/youtubeServiceTest.ts
- Add REQUEST_TIMEOUT_MS
- Add AUTHENTICATION_TIMEOUT_MS
- Add YOUTUBE_TIMEOUT_MS
- Add COURSE_CATALOGUE_TIMEOUT_MS
- Add LEARNER_RECORD_TIMEOUT_MS
- Add REGISTRY_SERVICE_TIMEOUT_MS
- Removed default timeouts in service config constructors
- Youtube API key configurable at constructor level
- Fixed/removed unit tests which needed fixing/weren't necessary, respectively
=> Idt feature lc 877 make all timeouts configurable

Dockerfile, package.json, src/applicationContext.ts, src/config/index.ts, src/config/ts-modules.ts, src/controllers/agencyTokenController.ts, src/controllers/courseController.ts, src/controllers/homeController.ts, src/controllers/learningProvider/cancellationPolicyController.ts, src/controllers/learningProvider/learningProviderController.ts, src/controllers/module/event/eventController.ts, src/controllers/module/linkModuleController.ts, src/controllers/module/moduleController.ts, src/controllers/organisationController.ts, src/controllers/searchController.ts, src/csrs/service/organisationalUnitService.ts, src/identity/auth.ts, src/lib/errorHandler.ts, src/server.ts, src/utils/logger.ts, src/youtube/youtubeService.ts
- Remove log4js logging
- Add winston logging
- Upgrade applicationinsights to 1.8.10
- Integrate winston and application insights
=> Idt feature lc 902 remove hammer upgrade logging

src/locale/en.json, views/page/error.html
This change updates the error message in the management (Admin) screen to:
> Sorry, there is a problem with this service
> We're looking into it. Please <a href='/sign-out'>sign out</a> and try again
=> Update service error wording

package-lock.json, package.json, src/controllers/agencyTokenController.ts, src/controllers/audience/audienceController.ts, src/controllers/courseController.ts, src/controllers/learningProvider/cancellationPolicyController.ts, src/controllers/learningProvider/learningProviderController.ts, src/controllers/learningProvider/termsAndConditionsController.ts, src/controllers/module/event/eventController.ts, src/controllers/module/faceToFaceModuleController.ts, src/controllers/module/fileController.ts, src/controllers/module/linkModuleController.ts, src/controllers/module/moduleController.ts, src/controllers/module/youtubeModuleController.ts, src/controllers/organisationController.ts, src/controllers/reportingController.ts, src/controllers/searchController.ts, src/server.ts
This change includes sanitation against cross-site scripting (XSS) on management endpoints
=> Secure endpoints against cross-site scripting

src/csrs/client/organisationalUnitClient.ts, src/csrs/model/organisationalUnit.ts, src/csrs/model/organisationalUnitTypeAhead.ts, src/csrs/service/organisationalUnitService.ts, src/lib/exception/resourceNotFoundError.ts, src/lib/http/jsonRestService.ts, test/unit/csrs/service/models/organisationalUnitTest.ts, test/unit/csrs/service/models/organisationalUnitTypeAheadTest.ts, test/unit/csrs/service/organisationalUnitServiceTest.ts
- Multiple fixes to how the cache is managed, as well as general robustness when dealing with organisational units
=> LC 1545 suggested required learning

src/applicationContext.ts
- ApplicationContext now creates dependencies in the correct order
=> LC-1618 Fix booking bug

src/config/index.ts, test/acceptance/features/steps/lib/mock-identity-service/index.js
This change updates the Client ID to match the new one created in [this pull request](https://github.com/Civil-Service-Human-Resources/identity-service/pull/226)
=> Update Client ID for local development

src/learner-record/index.ts
- Fix learner record endpoints for events
- Correct querystring for getting course records
=> Correct API endpoints for learner record interactions

src/controllers/audience/audienceController.ts, src/controllers/audience/model/AudienceViewModel.ts, src/controllers/courseController.ts, src/lib/audienceService.ts, test/unit/controllers/audience/audienceControllerTest.ts, test/unit/controllers/courseControllerTest.ts, views/component/audiences/template.njk, views/page/course/audience/configure-audience.html
- Introduce new view model for audiences which has a convenience function for rendering the department names server-side
- Remove reliance on filtering in template and render dep names directly from model
=> LC 2902 audience org code

src/controllers/models/filterSummary/filterSummary.ts, src/controllers/models/filterSummary/filterSummaryRow.ts, src/controllers/models/filterSummary/filterSummaryTag.ts, src/controllers/reporting/model/courseCompletionsGraphModel.ts, src/controllers/reporting/model/organisationFilterSummaryRow.ts, src/controllers/reporting/model/organisationFilterSummaryTag.ts, src/controllers/reporting/model/reportingFilterSummary.ts, src/report-service/index.ts, views/assets/styles/component/_components.scss, views/assets/styles/component/filterSummary.scss, views/component/chart/template.njk, views/component/filterSummary/filterSummaryRow/macro.njk, views/component/filterSummary/filterSummaryRow/template.njk, views/component/filterSummary/macro.njk, views/component/filterSummary/template.njk, views/component/nav/template.njk, views/page/reporting/courseCompletions/report.html
- New component to view selected filters in a row-by-row layout
- View models for new component
- Current organisation view for the completed learning report
=> LC-2712 organisation selection

src/controllers/models/filterSummary/filterSummaryTag.ts, src/controllers/reporting/courseCompletionsController.ts, src/controllers/reporting/model/chooseCoursesModel.ts, src/controllers/reporting/model/courseCompletionsSession.ts, src/controllers/reporting/model/courseFilterSummaryRow.ts, src/controllers/reporting/model/courseFilterSummaryTag.ts, src/controllers/reporting/model/reportingFilterSummary.ts, src/learning-catalogue/courseTypeAhead.ts, src/learning-catalogue/index.ts, src/report-service/index.ts, test/unit/controllers/reporting/courseCompletionsControllerTest.ts, test/unit/learning-catalogue/indexTest.ts, views/assets/styles/_global.scss, views/assets/styles/component/filterSummary.scss, views/component/filterSummary/filterSummaryRow/template.njk, views/page/reporting/courseCompletions/report.html
- Include course selections in filter panel above chart
- Change courses with hyperlink
- Remove individual courses with buttons
- Refactor course data
=> LC 2713/2714 course selection

src/config/index.ts, src/controllers/reporting/courseCompletionsController.ts, src/identity/identity.ts, src/report-service/model/getCourseAggregationParameters.ts, views/page/reporting/courseCompletions/report.html
- New reporting feedback banner
- Submit the banner properties server-side and log some user info for analytics
=> LC-2726 reporting solution feedback banner

package-lock.json, package.json, src/controllers/module/linkModuleController.ts, src/learning-catalogue/model/factory/linkFactory.ts
- Remove xss encoding on all link module endpoints
- Add xss on specific title/description link module fields
=> LC-3118 fix module encoding bug

src/config/index.ts, src/learning-catalogue/index.ts
- When searching for courses to report on in the new MVP report service, archived courses are now filtered out of the list
- Update default values for auth
=> LC-3183 filter archived courses out of course search

src/templating/tableService.ts
- Display numbers with commas for greater readability
=> LC-3184 formatted numbers

src/controllers/reporting/model/courseCompletionsSession.ts, src/controllers/reporting/utils.ts, src/identity/auth.ts, src/identity/identity.ts, src/report-service/model/course-completions/createReportRequestParameterFactory.ts, src/report-service/model/course-completions/createReportRequestParams.ts, test/unit/controllers/reporting/courseCompletionsControllerTest.ts, test/unit/csl-service/cslServiceClientTest.ts, test/unit/identity/authTest.ts
This change includes the full name of the user (retrieved from CSRS) in the course completion session. The full name is sent to the CSL Service for creating report requests.
=> LC-3163 / LC-3164: Get full name from profile session

views/page/reporting/courseCompletions/report.html
This change updates the date selection radio buttons:
* Removes the extendable date link
* Wraps the date radio buttons in a fieldset
* Adds a legend to the fieldset "Filter by date"
=> LC-3220: Accessibility: Update course completions date group inputs

views/assets/styles/component/_components.scss, views/assets/styles/component/summaryList.scss, views/page/course/audience/configure-audience.html
This change:
* Updates the Audience Configuration page:
* Replaces the summary list with GDS's summary list component
*  Make the actions links more accessible with visually hidden elements.
* Add `aria-label` tags to Delete buttons
* Add `role="link"` tags to Delete buttons
=> LC-3209: Accessibility: Update audience configuration page

src/identity/auth.ts
- Correctly logout when the logout flag is present
=> LC-3320 Correctly logout

views/component/filterSummary/template.njk, views/page/reporting/courseCompletions/report.html
This updates the reporting dashboard so that the filters show up on top instead of on the side.
=> LC-3291: Update reporting dashboard layout

src/csrs/service/csrsService.ts, src/identity/identity.ts, test/unit/csrs/service/csrsServiceTest.ts
- Convert user's domain to lowercase when checking their org eligibility
=> LC-3342 case sensitive domain check

.run-test/Template Mocha.run.xml, src/config/index.ts, src/controllers/courseController.ts, src/controllers/middleware/learningCatalogueMiddleware.ts, src/controllers/module/event/eventController.ts, src/controllers/organisationalUnit/organisationalUnitControllerBase.ts, src/controllers/organisationalUnit/organisationalUnitDomainsController.ts, src/controllers/reporting/courseCompletionsController.ts, src/csl-service/client.ts, src/csl-service/model/DownloadableFile.ts, src/csl-service/model/ReportResponse.ts, src/learning-catalogue/index.ts, src/learning-catalogue/service/entityService.ts, src/lib/courseService.ts, src/lib/errorHandler.ts, src/lib/exception/HttpException.ts, src/lib/exception/resourceNotFoundError.ts, src/lib/http/jsonRestService.ts, src/report-service/builder.ts, src/report-service/index.ts, src/report-service/model/course-completions/createReportRequestParameterFactory.ts, src/report-service/model/course-completions/createReportRequestParams.ts, test/unit/controllers/courseControllerTest.ts, test/unit/controllers/module/event/eventControllerTest.ts, test/unit/csl-service/cslServiceClientTest.ts, test/unit/learning-catalogue/service/entityServiceTest.ts, test/unit/lib/courseServiceTest.ts, test/unit/lib/http/jsonRestServiceTest.ts, views/page/not-found.html
- Add new endpoint for securely downloading course completion reports
- Send new endpoint in report requests
- Refactor some of the http request client logic
- New content for not found / forbidden pages
=> LC-3321 secure download

src/controllers/models/filterSummary/filterSummaryTag.ts, src/controllers/reporting/courseCompletionsController.ts, src/controllers/reporting/model/chooseCoursesModel.ts, src/controllers/reporting/model/courseCompletionsSession.ts, src/csl-service/client.ts, src/lib/http/jsonRestService.ts, src/report-service/index.ts, src/report-service/reportServicePageModelService.ts, test/unit/controllers/reporting/courseCompletionsControllerTest.ts, test/unit/csl-service/cslServiceClientTest.ts, views/page/reporting/courseCompletions/choose-courses.html, views/page/reporting/courseCompletions/report.html
- Add a radio button for selecting 'all learning' for the completions dashboard
- Add a new filter summary component for all learning
- Refactor some http call logic
=> LC-3290 all courses

views/component/list/template.njk, views/component/menu/template.njk, views/component/status/template.njk, views/component/statusWithLabel/template.njk, views/page/course/course-overview.html, views/page/organisation/add-edit-organisation.html, views/page/organisation/organisation-overview.html
Test Document: https://cshrdigitalandanalysis.atlassian.net/wiki/spaces/LPG/pages/3879600129/LC-3216-Management+UI+Incorrect+heading+structure
=> LC-3216 - Management UI - Incorrect heading structure

views/page/course/course-overview.html, views/page/course/course-preview.html, views/page/organisation/organisation-overview.html
Test Documents: https://cshrdigitalandanalysis.atlassian.net/wiki/spaces/LPG/pages/3882090497/LC-3229-Management+UI+Status+messages
=> LC-3229-Management UI - Status messages

src/learning-catalogue/index.ts, src/lib/courseService.ts
Correctly update course title typeahead when updating a course title
=> LC 3481 update course typeahead

src/controllers/module/event/eventController.ts, src/controllers/reporting/registeredLearnersController.ts, src/identity/identity.ts, src/server.ts, views/component/nav/template.njk, views/page/reporting/index.html
- Remove event viewer role check from router middleware, reapply to endpoint middleware
- Refactor RBAC code
- Introduce new registered learner controller
- Link to registered learner in reporting index
=> LC-3507 View registered learner dashboard

src/config/index.ts, src/server.ts
- Add `HEALTH_CHECK_ENABLED` and `HEALTH_CHECK_ENDPOINT` environment variables
- Add an unauthorised healthcheck endpoint to enable Azure health monitoring
=> LC-3688 Add a configurable secret health check

src/controllers/courseController.ts, views/page/course/course-preview.html, views/page/course/course-visibility-confirmation.html, views/page/course/course-visibility.html
This change updates the course details page so that admins are able to update the visibility of a course after it has been created
=> LC-3624: Update course visibility

views/assets/js/report-download.js, views/component/filterSummary/template.njk, views/page/reporting/courseCompletions/report.html
- Include csrf token on reporting
=> LC-3735 csrf on reporting

src/csrs/model/organisationalUnit.ts, src/csrs/service/csrsService.ts, src/lib/redisCache.ts, test/unit/csrs/service/csrsServiceTest.ts, views/page/reporting/courseCompletions/report.html
- Prevent Tier 1 code from entering an endless loop
- Add some more logging for when the cache is accessed
=> LC-3758 Tier 1 loop fix
